#!/usr/bin/env bash
# HomeFlix installer for Linux + systemd.
#
#   ./install.sh                  interactive: asks for your video folder, then does everything
#   ./install.sh --yes --library /mnt/videos     no questions
#   ./install.sh --no-service     set everything up but don't touch systemd
#   ./install.sh --uninstall      remove the service (your data/library are left alone)
#
# Safe to re-run (e.g. after `git pull`): it keeps your homeflix.env and database,
# migrates, and restarts the service. Run it as your normal user, not root --
# it only uses sudo for the systemd/apt steps.
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$APP_DIR/homeflix.env"
UNIT_TEMPLATE="$APP_DIR/deploy/homeflix.service.in"
UNIT_OUT="$APP_DIR/homeflix.service"
UNIT_DEST="/etc/systemd/system/homeflix.service"
UNIT_MARK="# Generated by HomeFlix install.sh"
PY="$APP_DIR/venv/bin/python"

# Oldest JS runtimes yt-dlp's YouTube challenge solver accepts. Keep in sync
# with _MIN_RUNTIME in library/downloader.py (which mirrors yt-dlp itself):
# anything older (e.g. distro Node 18) is silently ignored and every download fails.
MIN_DENO=2.3.0; MIN_BUN=1.2.11; MIN_NODE=22.0.0

LIBRARY=""; PORT=""; BIND=""; SVC_USER=""
ASSUME_YES=0; NO_SERVICE=0; NO_DENO=0; UNINSTALL=0; INTERACTIVE=0

say()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m  %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxx\033[0m  %s\n' "$*" >&2; exit 1; }

usage() { sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'; cat <<'U'

Options:
  --library PATH   folder with your videos (HOMEFLIX_LIBRARY)
  --port N         port to listen on (default 8002)
  --bind ADDR      0.0.0.0 = reachable from phones/TVs on your LAN (default),
                   127.0.0.1 = this machine only (use with nginx, see README)
  --user NAME      user the service runs as (default: you)
  --yes            never ask; use defaults/flags
  --no-service     skip the systemd step
  --no-deno        don't install Deno even if no suitable JS runtime is found
  --uninstall      stop + remove the systemd service
U
}

# ---- prompts ----------------------------------------------------------------
ask() {  # ask "Prompt" default  -> prints the answer
  local prompt=$1 def=$2 ans=""
  if (( ! INTERACTIVE )); then printf '%s' "$def"; return; fi
  read -r -p "$prompt [$def]: " ans </dev/tty || ans=""
  printf '%s' "${ans:-$def}"
}
confirm() {  # confirm "Question" y|n  -> exit status
  local q=$1 def=${2:-y} ans="" hint="[Y/n]"
  [ "$def" = n ] && hint="[y/N]"
  if (( ! INTERACTIVE )); then [ "$def" = y ]; return; fi
  read -r -p "$q $hint " ans </dev/tty || ans=""
  ans=${ans:-$def}; [[ $ans =~ ^[Yy] ]]
}

# ---- version helpers (sourceable for tests) ------------------------------------
exe_version() { "$1" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n1 || true; }
ver_ge() {  # ver_ge have want -> true if have >= want
  [ -n "$1" ] && [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -n1)" = "$2" ]
}
have_js_runtime() {
  local p
  for p in "$APP_DIR/.deno/bin/deno" "$(command -v deno || true)"; do
    [ -n "$p" ] && [ -x "$p" ] && ver_ge "$(exe_version "$p")" "$MIN_DENO" && return 0
  done
  p="$(command -v bun || true)"; [ -n "$p" ] && [ -x "$p" ] && ver_ge "$(exe_version "$p")" "$MIN_BUN" && return 0
  p="$(command -v node || true)"; [ -n "$p" ] && [ -x "$p" ] && ver_ge "$(exe_version "$p")" "$MIN_NODE" && return 0
  return 1
}

# ---- steps ------------------------------------------------------------------
as_root() { if [ "$(id -u)" -eq 0 ]; then "$@"; else sudo "$@"; fi; }

install_system_packages() {
  local missing=()
  command -v ffmpeg  >/dev/null 2>&1 && command -v ffprobe >/dev/null 2>&1 || missing+=(ffmpeg)
  command -v curl    >/dev/null 2>&1 || missing+=(curl)
  command -v unzip   >/dev/null 2>&1 || missing+=(unzip)   # the Deno installer needs it
  "$PY_BOOT" -c 'import ensurepip, venv' >/dev/null 2>&1 || missing+=(python3-venv)
  (( ${#missing[@]} )) || return 0
  if command -v apt-get >/dev/null 2>&1; then
    say "Missing system packages: ${missing[*]}"
    if confirm "Install them with apt?" y; then
      as_root apt-get update -qq && as_root apt-get install -y "${missing[@]}"
      return 0
    fi
  fi
  warn "Please install: ${missing[*]}  (ffmpeg + ffprobe are required; the rest are needed by this script)"
  command -v ffmpeg >/dev/null 2>&1 || die "ffmpeg is required."
}

setup_venv() {
  say "Python environment (venv/)"
  [ -x "$PY" ] || "$PY_BOOT" -m venv "$APP_DIR/venv"
  "$PY" -m pip install --quiet --upgrade pip || warn "Couldn't upgrade pip (continuing)."
  "$PY" -m pip install --quiet -r "$APP_DIR/requirements.txt" gunicorn \
    || die "pip couldn't install the dependencies. Check your network / pip index (pip config list) and re-run."
}

setup_js_runtime() {
  if have_js_runtime; then say "JavaScript runtime for yt-dlp: OK"; return 0; fi
  local old=""
  command -v node >/dev/null 2>&1 && old=" (found Node $(exe_version "$(command -v node)"), which is too old)"
  warn "No JavaScript runtime new enough for yt-dlp (needs Deno $MIN_DENO+ or Node $MIN_NODE+)$old."
  warn "Without one every YouTube download fails at the \"challenge\" step."
  (( NO_DENO )) && { warn "--no-deno given: skipping. Install Deno yourself, then restart HomeFlix."; return 0; }
  if ! confirm "Install Deno into $APP_DIR/.deno (official installer from deno.land, no root needed)?" y; then
    warn "Skipped. Downloads won't work until Deno/Node 22+ is installed."; return 0
  fi
  local tmp; tmp="$(mktemp)"
  curl -fsSL https://deno.land/install.sh -o "$tmp" || { rm -f "$tmp"; die "Couldn't download the Deno installer."; }
  local log; log="$(mktemp)"
  if ! DENO_INSTALL="$APP_DIR/.deno" sh "$tmp" --no-modify-path </dev/null >"$log" 2>&1; then
    tail -n 15 "$log" >&2; rm -f "$tmp" "$log"; die "Deno install failed."
  fi
  rm -f "$tmp" "$log"
  have_js_runtime && say "Deno installed" || warn "Deno installed but isn't new enough?? Check $APP_DIR/.deno/bin/deno --version"
}

lan_ips() { for ip in $(hostname -I 2>/dev/null || true); do [[ $ip == *.* ]] && printf '%s\n' "$ip"; done; }

# Prints KEY="VALUE" lines for the HOMEFLIX_* settings of an existing hand-written
# service (the README's manual unit), so migrating to this installer keeps them.
import_env_from_unit() {
  local re='^[[:space:]]*Environment="(HOMEFLIX_[A-Z_]+)=(.*)"[[:space:]]*$' line k v
  [ -r "$UNIT_DEST" ] || return 0
  while IFS= read -r line; do
    [[ $line =~ $re ]] || continue
    k=${BASH_REMATCH[1]}; v=${BASH_REMATCH[2]}   # copy now: the next =~ would overwrite BASH_REMATCH
    if [[ $v =~ [\"\$\`\\] ]]; then
      warn "Not importing $k (has special characters): add it to homeflix.env by hand." >&2; continue
    fi
    printf '%s="%s"\n' "$k" "$v"
  done < "$UNIT_DEST"
}

write_env_file() {
  if [ -f "$ENV_FILE" ]; then say "Keeping existing settings: $ENV_FILE"; return 0; fi
  if [ -z "$LIBRARY" ] && [ -r "$UNIT_DEST" ] && grep -q 'Environment="HOMEFLIX_' "$UNIT_DEST" \
     && ! grep -qF "$UNIT_MARK" "$UNIT_DEST"; then
    say "Found an existing homeflix service with settings in $UNIT_DEST"
    if confirm "Import them (library, hosts, HTTPS origins, ...) into homeflix.env?" y; then
      local imported; imported="$(import_env_from_unit)"
      if grep -q '^HOMEFLIX_LIBRARY=' <<<"$imported"; then
        local key=""
        if ! grep -q '^HOMEFLIX_SECRET_KEY=' <<<"$imported"; then
          key="HOMEFLIX_SECRET_KEY=\"$("$PY" -c 'import secrets; print(secrets.token_urlsafe(50))')\""
          warn "Your old service had no HOMEFLIX_SECRET_KEY (it ran on the public dev key). Generated one; everyone signs in once more."
        fi
        ( umask 077; { echo "# Imported from $UNIT_DEST by install.sh. Edit, then: sudo systemctl restart homeflix"
                       echo "$imported"; [ -n "$key" ] && echo "$key"; true; } > "$ENV_FILE" )
        chmod 600 "$ENV_FILE"
        say "Wrote $ENV_FILE with your existing settings"; return 0
      fi
      warn "No HOMEFLIX_LIBRARY in the old service; falling back to a fresh setup."
    fi
  fi
  local lib=${LIBRARY:-}
  [ -n "$lib" ] || lib="$(ask "Folder with your videos" "${HOME}/Videos")"
  lib="${lib/#\~/$HOME}"
  [[ $lib =~ [\"\$\`\\] ]] && die "Library path can't contain \" \$ \` or \\ characters."
  if [ ! -d "$lib" ]; then
    confirm "Folder $lib doesn't exist. Create it?" y || die "Library folder is required."
    mkdir -p "$lib"
  fi
  local hosts="localhost,127.0.0.1" ip
  for ip in $(lan_ips); do hosts+=",$ip"; done
  hosts+=",$(hostname),$(hostname).local"
  local key; key="$("$PY" -c 'import secrets; print(secrets.token_urlsafe(50))')"
  ( umask 077; cat > "$ENV_FILE" <<ENV
# HomeFlix settings (read by the systemd service and by install.sh). Edit, then:
#   sudo systemctl restart homeflix
HOMEFLIX_LIBRARY="$lib"
HOMEFLIX_SECRET_KEY="$key"
# Hostnames/IPs this server answers to (Django rejects any other Host header):
HOMEFLIX_HOSTS="$hosts"
# Behind nginx with HTTPS? Uncomment and see README ("Run behind nginx"):
# HOMEFLIX_ORIGINS="https://192.168.1.50:8443"
# HOMEFLIX_HTTPS=1
# Let anyone on the LAN browse/watch without an account (still read-only):
# HOMEFLIX_PUBLIC=1
# Path shown under the player so you can jump to the file from another PC (see README):
# HOMEFLIX_REMOTE_ROOT=
ENV
  )
  chmod 600 "$ENV_FILE"
  say "Wrote $ENV_FILE (secret key generated, mode 600)"
}

load_env() { set -a; . "$ENV_FILE"; set +a; }

setup_django() {
  load_env
  say "Database + static files"
  "$PY" manage.py migrate --noinput -v 0
  "$PY" manage.py collectstatic --noinput -v 0 >/dev/null
  if ! "$PY" manage.py shell -c 'import sys; from django.contrib.auth import get_user_model as g; sys.exit(0 if g().objects.filter(is_staff=True).exists() else 1)' >/dev/null 2>&1; then
    if (( INTERACTIVE )); then
      say "Create your owner login (the account that can manage the library):"
      "$PY" manage.py createsuperuser </dev/tty
    else
      warn "No owner account yet. Create one:  $PY manage.py createsuperuser"
    fi
  fi
  if confirm "Scan your video library now? (can take a while for big libraries; you can also press Rescan in the app)" "$( (( INTERACTIVE )) && echo y || echo n )"; then
    "$PY" manage.py scan
  else
    say "Library not scanned yet: the app scans it in the background every 30 min, or press Rescan in the Manage (...) menu."
  fi
}

render_unit() {
  sed -e "s|@APP_DIR@|$APP_DIR|g" -e "s|@USER@|$SVC_USER|g" \
      -e "s|@BIND@|$BIND|g" -e "s|@PORT@|$PORT|g" "$UNIT_TEMPLATE" > "$UNIT_OUT"
}

install_service() {
  command -v systemctl >/dev/null 2>&1 || { warn "systemd not found; skipping the service. Run manually: $APP_DIR/venv/bin/gunicorn config.wsgi:application --bind $BIND:$PORT --workers 3 --worker-class gthread --threads 8 --timeout 120"; return 0; }
  render_unit
  say "Service file: $UNIT_OUT"
  if [ -f "$UNIT_DEST" ] && ! grep -qF "$UNIT_MARK" "$UNIT_DEST" && ! cmp -s "$UNIT_OUT" "$UNIT_DEST"; then
    warn "$UNIT_DEST already exists and wasn't created by this installer (e.g. the manual unit from the README)."
    confirm "Replace it? (a copy is saved as $UNIT_DEST.bak)" n || { warn "Left it alone. Generated unit is at $UNIT_OUT"; return 0; }
    as_root cp "$UNIT_DEST" "$UNIT_DEST.bak"
  fi
  if ! systemctl is-active --quiet homeflix 2>/dev/null && command -v ss >/dev/null 2>&1; then
    local listening   # captured first: `ss | grep -q` would trip pipefail via SIGPIPE
    listening="$(ss -ltnH 2>/dev/null | awk '{print $4}' || true)"
    if grep -qE "[:.]$PORT\$" <<<"$listening"; then
      warn "Port $PORT is already in use by another program. Re-run with --port <other>."
    fi
  fi
  as_root install -m 644 "$UNIT_OUT" "$UNIT_DEST"
  as_root systemctl daemon-reload
  as_root systemctl enable homeflix >/dev/null 2>&1
  as_root systemctl restart homeflix
  say "Service enabled (starts on boot) and (re)started"
}

wait_for_http() {
  command -v curl >/dev/null 2>&1 || return 0
  local i
  for i in 1 2 3 4 5 6 7 8 9 10; do
    curl -fsS -o /dev/null --max-time 3 "http://127.0.0.1:$PORT/login/" 2>/dev/null && return 0
    sleep 1
  done
  return 1
}

summary() {
  echo
  if wait_for_http; then say "HomeFlix is running."; else warn "Not answering yet. Check:  journalctl -u homeflix -e"; fi
  echo "  Open:     http://localhost:$PORT/"
  for ip in $(lan_ips); do echo "            http://$ip:$PORT/   (phones / TVs on your network)"; done
  echo "  Settings: $ENV_FILE   (then: sudo systemctl restart homeflix)"
  echo "  Logs:     journalctl -u homeflix -f"
  echo "  Update:   git pull && ./install.sh"
  echo "  Remove:   ./install.sh --uninstall"
  echo
  echo "  Playlist downloads: open Manage (…) -> Download from playlist, paste your YouTube cookies once."
}

uninstall() {
  command -v systemctl >/dev/null 2>&1 || die "systemd not found."
  say "Removing the homeflix service (your videos, database and settings stay)"
  as_root systemctl disable --now homeflix 2>/dev/null || true
  as_root rm -f "$UNIT_DEST"
  as_root systemctl daemon-reload
  say "Done."
}

main() {
  while [ $# -gt 0 ]; do
    case $1 in
      --library) LIBRARY=${2:?}; shift 2 ;;
      --port)    PORT=${2:?}; shift 2 ;;
      --bind)    BIND=${2:?}; shift 2 ;;
      --user)    SVC_USER=${2:?}; shift 2 ;;
      --yes|-y)  ASSUME_YES=1; shift ;;
      --no-service) NO_SERVICE=1; shift ;;
      --no-deno) NO_DENO=1; shift ;;
      --uninstall) UNINSTALL=1; shift ;;
      -h|--help) usage; exit 0 ;;
      *) usage; die "Unknown option: $1" ;;
    esac
  done
  [ "$(uname -s)" = Linux ] || die "This installer is for Linux. On Windows use run-homeflix.bat."
  [ "$(id -u)" -ne 0 ] || die "Run as your normal user, not root (sudo is used only where needed)."
  (( UNINSTALL )) && { uninstall; exit 0; }
  [ -t 0 ] && (( ! ASSUME_YES )) && INTERACTIVE=1

  PY_BOOT="$(command -v python3 || true)"; [ -n "$PY_BOOT" ] || die "python3 not found (sudo apt install python3 python3-venv)."
  "$PY_BOOT" -c 'import sys; sys.exit(sys.version_info < (3, 10))' || die "Python 3.10+ is required."
  [ -f "$UNIT_TEMPLATE" ] || die "Missing $UNIT_TEMPLATE (run this from a full HomeFlix checkout)."

  SVC_USER=${SVC_USER:-$(id -un)}
  if [ -z "$PORT" ]; then PORT="$(ask "Port" 8002)"; fi
  [[ $PORT =~ ^[0-9]+$ ]] && (( PORT >= 1 && PORT <= 65535 )) || die "Port must be a number between 1 and 65535."
  if [ -z "$BIND" ]; then
    if (( INTERACTIVE )); then
      confirm "Reachable from other devices on your network (phone, TV)? (No = this machine only, for use behind nginx)" y \
        && BIND=0.0.0.0 || BIND=127.0.0.1
    else BIND=0.0.0.0; fi
  fi

  install_system_packages
  setup_venv
  setup_js_runtime
  write_env_file
  setup_django
  if (( NO_SERVICE )); then
    render_unit
    say "Skipped systemd (--no-service). Generated unit: $UNIT_OUT"
    echo "  Run by hand:  set -a; . $ENV_FILE; set +a; $APP_DIR/venv/bin/gunicorn config.wsgi:application --bind $BIND:$PORT --workers 3 --worker-class gthread --threads 8 --timeout 120"
  else
    install_service
    summary
  fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then main "$@"; fi
