"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! The old
# hardcoded key was committed to git (and is public in history), so it can
# never be trusted again -- generate a fresh one and pass it via env:
#   python -c "from django.core.management.utils import get_random_secret_key as g; print(g())"
# The literal fallback below is for a throwaway local/dev DB only.
SECRET_KEY = os.environ.get(
    "HOMEFLIX_SECRET_KEY",
    "django-insecure-dev-only-not-for-production-use-HOMEFLIX_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production! DEBUG=True
# renders full tracebacks (including settings) to any visitor on error.
# Set HOMEFLIX_DEBUG=1 for local development only.
DEBUG = os.environ.get("HOMEFLIX_DEBUG") == "1"

# Set HOMEFLIX_HOSTS to a comma-separated list of hostnames/IPs this server
# is reachable as (e.g. "192.168.1.50,homeflix.example.com"). Required once
# DEBUG=False -- Django rejects requests with an unrecognized Host header.
_hosts = os.environ.get("HOMEFLIX_HOSTS", "").strip()
ALLOWED_HOSTS = [h.strip() for h in _hosts.split(",") if h.strip()] or ["localhost", "127.0.0.1"]

# Set HOMEFLIX_PUBLIC=1 to let anyone browse/search/watch/stream without an
# account (a "YouTube, not Fort Knox" mode for casually sharing the link) --
# see library/auth.py's public_when_enabled decorator for exactly which
# views that exempts. Anything that writes shared library data (favorite,
# rating, playlists, notes) or touches the filesystem/catalog (owner-only)
# still requires logging in. Off by default -- an existing deployment's
# behavior doesn't change unless this is explicitly set.
PUBLIC_ACCESS = os.environ.get("HOMEFLIX_PUBLIC") == "1"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Default-deny: every view requires login unless decorated with
    # @login_not_required (see library/views.py: pwa_manifest, pwa_icon) or
    # it's the login view itself (library/auth.py).
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Only needed once DEBUG=False (Django's dev server stops auto-serving
# /static/ then) -- mainly for /admin's CSS. Run `manage.py collectstatic`
# and point nginx at this folder (see nginx-homeflix.conf).
STATIC_ROOT = BASE_DIR / "staticfiles"


# ---- Authentication / sessions ----------------------------------------------
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

# TVs and phones must stay logged in -- the session is the only credential,
# and re-typing a password on an LG remote is painful. A year-long cookie
# refreshed on every request effectively never expires under normal use.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# Cookies are scoped by host, NOT port -- Django's default `sessionid` /
# `csrftoken` names are shared with every other Django app on this machine
# (another project on :8000 overwrites ours and logs us out). Namespace them.
SESSION_COOKIE_NAME = "homeflix_sessionid"
CSRF_COOKIE_NAME = "homeflix_csrftoken"

# Only mark cookies Secure when actually served over HTTPS (nginx, see
# nginx-homeflix.conf) -- if this were unconditional, a plain LAN
# http:// deployment would silently fail to log in.
_https = os.environ.get("HOMEFLIX_HTTPS") == "1"
SESSION_COOKIE_SECURE = _https
CSRF_COOKIE_SECURE = _https

# Filesystem cache (stdlib, no extra dependency) shared across gunicorn
# workers -- used to throttle repeated failed logins per IP (library/auth.py),
# the same reason services.start_hls tracks sessions on the filesystem
# instead of in-process.
CACHE_DIR = str(BASE_DIR / "cache")
os.makedirs(CACHE_DIR, exist_ok=True)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": CACHE_DIR,
    }
}


# ---- HomeFlix configuration -------------------------------------------------

# The folder that holds all your videos (scanned recursively).
# Override with the HOMEFLIX_LIBRARY environment variable.
LIBRARY_ROOT = os.environ.get("HOMEFLIX_LIBRARY", str(BASE_DIR / "media_library"))

# Where generated thumbnails are stored.
THUMBNAIL_DIR = str(BASE_DIR / "thumbnails")

# Video file extensions treated as playable media. Everything else
# (txt, png, jpeg, ...) is ignored by the scanner and left untouched.
VIDEO_EXTENSIONS = {".mp4", ".webm", ".mkv", ".mov", ".m4v", ".avi"}

# Codecs/containers that desktop browsers generally CANNOT play via <video>.
# These play through the live HLS transcode path (see services.start_hls).
NON_BROWSER_CONTAINERS = {".mkv", ".avi"}
NON_BROWSER_VCODECS = {"hevc", "h265", "mpeg4", "msmpeg4v3", "wmv3"}

os.makedirs(THUMBNAIL_DIR, exist_ok=True)

# ---- Reverse-proxy / HTTPS (nginx in front) ---------------------------------
# When behind nginx terminating TLS, trust the forwarded scheme and the HTTPS
# origin so POST/CSRF works. Set HOMEFLIX_ORIGINS to your https URL(s),
# comma-separated, e.g. "https://192.168.1.50:8443,https://dorm.local".
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
_origins = os.environ.get("HOMEFLIX_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _origins.split(",") if o.strip()]

# Where browser-friendly converted copies are written (kept OUT of LIBRARY_ROOT
# so the scanner never re-imports them).
CONVERTED_DIR = str(BASE_DIR / "converted")
os.makedirs(CONVERTED_DIR, exist_ok=True)

# Temp dir for live HLS transcode segments (one subfolder per video while it's
# being watched, cleaned up on close / idle). Also kept OUT of LIBRARY_ROOT.
HLS_DIR = str(BASE_DIR / "hls")
os.makedirs(HLS_DIR, exist_ok=True)

# Cached WebVTT subtitles converted from sidecar (.srt/.ass/...) or embedded
# mkv subtitle tracks. Also kept OUT of LIBRARY_ROOT.
SUBTITLE_DIR = str(BASE_DIR / "subtitles")
os.makedirs(SUBTITLE_DIR, exist_ok=True)

# Playlist downloader (library/downloader.py): holds the pasted YouTube
# cookies.txt and per-run marker files. Also kept OUT of LIBRARY_ROOT.
YTDL_DIR = str(BASE_DIR / "ytdl")
os.makedirs(YTDL_DIR, exist_ok=True)

# Library page size for infinite scroll.
PAGE_SIZE = 60

# UNC path shown (and copied) under the player so you can jump to the file
# from another machine on the LAN, e.g. \\192.168.1.39\YouTube\2026-01\05\name.mp4.
# Override with HOMEFLIX_REMOTE_ROOT; leave blank to just show the real local path.
REMOTE_ROOT = os.environ.get("HOMEFLIX_REMOTE_ROOT", r"\\192.168.1.39\YouTube")

# Background scan interval (minutes). Set 0 to disable.
SCAN_INTERVAL_MINUTES = 30
