"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t*238c1cxca(qku_jc*d##7d3chdgs5840-@kil=#lotn3()gm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # personal LAN server


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ---- HomeFlix configuration -------------------------------------------------
import os

# The folder that holds all your videos (scanned recursively).
# Override with the HOMEFLIX_LIBRARY environment variable.
LIBRARY_ROOT = os.environ.get("HOMEFLIX_LIBRARY", str(BASE_DIR / "media_library"))

# Where generated thumbnails are stored.
THUMBNAIL_DIR = str(BASE_DIR / "thumbnails")

# Video file extensions treated as playable media. Everything else
# (txt, png, jpeg, ...) is ignored by the scanner and left untouched.
VIDEO_EXTENSIONS = {".mp4", ".webm", ".mkv", ".mov", ".m4v", ".avi"}

# Codecs/containers that desktop browsers generally CANNOT play via <video>.
NON_BROWSER_CONTAINERS = {".mkv", ".avi"}
NON_BROWSER_VCODECS = {"hevc", "h265", "mpeg4", "msmpeg4v3", "wmv3"}

os.makedirs(THUMBNAIL_DIR, exist_ok=True)

# ---- Reverse-proxy / HTTPS (nginx in front) ---------------------------------
# When behind nginx terminating TLS, trust the forwarded scheme and the HTTPS
# origin so POST/CSRF works. Set HOMEFLIX_ORIGINS to your https URL(s),
# comma-separated, e.g. "https://192.168.1.50:8443,https://dorm.local".
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
_origins = os.environ.get("HOMEFLIX_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _origins.split(",") if o.strip()]

# Where browser-friendly converted copies are written (kept OUT of LIBRARY_ROOT
# so the scanner never re-imports them).
CONVERTED_DIR = str(BASE_DIR / "converted")
os.makedirs(CONVERTED_DIR, exist_ok=True)

# Library page size for infinite scroll.
PAGE_SIZE = 60

# Background scan interval (minutes). Set 0 to disable.
SCAN_INTERVAL_MINUTES = 30
